#!/usr/bin/env bash
set -euo pipefail

if [[ -x /usr/libexec/rpm-ostree/wrapped/dracut ]]; then
	dracut=/usr/libexec/rpm-ostree/wrapped/dracut
else
	dracut=/usr/bin/dracut
fi

mapfile -t kernels < <(find /usr/lib/modules -mindepth 1 -maxdepth 1 -type d -printf '%f\n')
[[ ${#kernels[@]} -eq 1 ]]

for kernel in "${kernels[@]}"; do
	initramfs="/usr/lib/modules/$kernel/initramfs.img"
	"$dracut" \
		--kver "$kernel" \
		--force \
		--add ostree \
		--no-hostonly \
		--reproducible \
		"$initramfs"
	chmod 0600 "$initramfs"
done
