#!/usr/bin/bash

dnf5 -y install \
    @cosmic-desktop-environment \
    flatpak \
    seahorse \
    gnome-keyring \
    libsecret \
    gvfs \
    gvfs-afc \
    gvfs-gphoto2 \
    gvfs-mtp \
    gvfs-smb \
    gvfs-fuse \
    NetworkManager-adsl \
    NetworkManager-wifi \
    cups \
    cups-filters \
    pipewire-alsa \
    pipewire-jack \
    pipewire-pulseaudio \
    wireplumber \
    alsa-utils \
    kernel-modules-extra \

dnf5 -y remove \
    dnf-makecache.timer \
    PackageKit \
    libreoffice-* \

systemctl set-default graphical.target
systemctl enable cosmic-greeter.service

systemctl enable NetworkManager.service
systemctl enable firewalld.service
systemctl enable bluetooth.service
systemctl enable cups.service
