#!/usr/bin/bash

# Exclude packages incompatible with bootc/ostree
# Based on: https://pagure.io/workstation-ostree-config/blob/main/f/fedora-common-ostree-pkgs.yaml
EXCLUDES=(
    # PackageKit - incompatible with bootc
    "PackageKit*"
    # ABRT - incompatible with ostree
    "abrt-cli"
    "abrt-desktop"
    "abrt-java-connector"
    # Printing - cups-pk-helper uses PackageKit
    "cups-pk-helper"
)

EXCLUDE_ARGS=()
for pkg in "${EXCLUDES[@]}"; do
    EXCLUDE_ARGS+=(--exclude="$pkg")
done

dnf5 -y install "${EXCLUDE_ARGS[@]}" \
    @cosmic-desktop-environment \
    xdg-desktop-portal-gtk \
    gvfs-afc \
    gvfs-gphoto2 \
    gvfs-mtp \
    NetworkManager-adsl \
    NetworkManager-wifi \
    cups \
    cups-filters \
    pipewire-alsa \
    pipewire-pulseaudio \
    wireplumber \
    alsa-utils \
    kernel-modules-extra \
