#!/usr/bin/bash

set -ouex pipefail

sh -c "cat > /etc/yum.repos.d/vivaldi.repo <<'EOF'
  [vivaldi]
  name=vivaldi
  baseurl=https://repo.vivaldi.com/archive/rpm/x86_64
  enabled=1
  gpgcheck=1
  gpgkey=https://repo.vivaldi.com/archive/linux_signing_key.pub
  EOF"

rpm-ostree install vivaldi-stable
